### ISSUE TITLE
Providing software assets for tasks

### ISSUE THREAD

**Issue by TMiguelT** [dnanexus-rnd/dxWDL#26]
When writing DNAnexus applets, it is possible to provide tools (for example, applications like `bwa`) needed by the applet in the `resources` directory, or to use the `assetDepends` or `execDepends` keys in `dxapp.json`. I can't work out how to ensure these dependencies are present in a dxWLD `task`. WDL seems to support this information using the ` runtime { }` block, but I'm not sure how dxWDL would use this information.

**Comment by orodeh** [comment]
The WDL way to do this, is to create a docker image with the necessary software tools. The runtime block can then specify the docker image, the amount of RAM required, etc.
