### ISSUE TITLE
support for GCE-style disk spec in runtime block

### ISSUE THREAD

**Issue by dpark01** [dnanexus-rnd/dxWDL#68]
My current WDL, which targets Google JES execution via Cromwell, will often contain something like this in the runtime block of a task:
```
    disks: "local-disk 375 LOCAL, /mnt/db 375 LOCAL"
```

On GCE, this attaches ephemeral local scratch disk, using one for the main drive, and another attached at a special mount point. GCE allows up to eight local disks per instance, and the Google backend for Cromwell ignores the disk size parameter if LOCAL is specified (since they're always 375GB on GCE).

dxWDL complains about this line in my runtime block, even if I manually specify `dx_instance_type` as well:
```
java.lang.Exception: Can't parse disk space specification local-disk 375 LOCAL, /mnt/db 375 LOCAL
```

On DNAnexus default AWS instances, the disks are always local (e.g. `c3` instances) and you tend to gang them together in a RAID or something and present them as a single drive. I'm wondering if it would be possible for dxWDL to add the following abilities:

1. Successfully parse the above GCE-targeted disks specification without error (multiple disks, different mount points).
2. Use the sum of all requested disk sizes to decide on a standard dx_instance_type that presents a single drive with sufficient total storage.
3. Instead of presenting them as individually mounted file systems (as GCE does), keep it simple and just `mkdir` or symlink the requested mount points so that the code can at least write data to the path specified.

That would make it a bit easier to write portable WDL between the two execution environments. In these particular tasks, I'm unable to simplify the disks spec to a single drive and still execute on Cromwell+Google, because these tasks are much slower on Google's persistent network-attached drives, and a single Google local scratch disk is not big enough for the task.

**Comment by ohad-rodeh** [comment]
@dpark01 This is an interesting, and new, portability problem. I think I can do what you are asking, although I want to think about it some more.

Aside from this problem, does your workflow run with dxWDL+DNAx?

**Comment by dpark01** [comment]
This particular workflow does not compile, so I have not run it on DNAnexus. I have compiled others via dxWDL and have shared that project with you. The workflows I am attempting to compile are [here](https://github.com/broadinstitute/viral-ngs/tree/dp-wdl/pipes/WDL). The fail-to-compile workflows are any of the ones involving kraken or demux. The traditional (non-WDL) DNAnexus workflows for the same processes are [here](https://github.com/dnanexus/viral-ngs/tree/dnanexus/demux).

**Comment by dpark01** [comment]
Ok, while this still may be a nice feature to add later on, I've unblocked my own situation by moving this into the default runtime block in the config file for cromwell and adding some shell code to the task's command section to determine if certain mount points exist or not.

**Comment by orodeh** [comment]
I would say that this is a portability problem, much better solved at the WDL specification level. Of course, that doesn't actually solve the problem.

**Comment by dpark01** [comment]
On a personal level, I've found ways around this and am fine if we close the issue.
