### ISSUE TITLE
any support for dx file patterns in inputSpec?

### ISSUE THREAD

**Issue by dpark01** [dnanexus-rnd/dxWDL#72]
Is there currently any support in dxWDL to populate the "patterns" portion of a file in the inputSpec? E.g.:

```
"inputSpec": [
    {
      "name": "assembly",
      "class": "file",
      "patterns": ["*.fasta"]
    }
]
```

Maybe there's a DNAnexus-specific way to co-opt WDL's `parameter_meta` or `meta` in some way for this purpose? At first glance, `parameter_meta` looks a bit too limiting as-is, but I don't know if you've pondered ways of doing this or have proposed anything to the OpenWDL folks about it?

**Comment by orodeh** [comment]
I am working on adding it to the WDL language, but it isn't there right now. I wrote a branch with the [necessary modifications](https://github.com/dnanexus-rnd/wdl4s/tree/declaration_attributes) three months ago. Meanwhile the landscape has changed, the wdl4s repository was folded into Cromwell, and wdl became openWDL. 

Basically, the idea is to support attributes for declarations. This would allow patterns and help strings, for example. 

You can mention it to [Jeff Gentry](https://github.com/geoffjentry), he is the the technical team lead for WDL at the Broad.
