### ISSUE TITLE
dx-docker pull speed

### ISSUE THREAD

**Issue by dpark01** [dnanexus-rnd/dxWDL#77]
I'm seeing some somewhat erratic docker image pull times for workflows executed by dxWDLrt. Typical pull time seems to be about 3-4mins which seems par for the course (I can achieve 2.5-3 minute pulls of my image on a GCE or AWS instance running CoreOS). But every once in a while, a DNAnexus job will take 20 or sometimes even 40 mins just to pull the docker image (example: job-F8G5KyQ09y3bJYjqB23XJgBQ).

Do you have `/var/lib/docker` pointing to a local ephemeral disk mount, or is it on an EBS/root volume? (Or maybe dx-docker doesn't use a daemon, but it must be saving / unpacking the ACI somewhere)

In my own attempts to time pull behavior outside of DNAnexus, it seems that `docker pull` speed has almost nothing to do with available network bandwidth, but is either bound by disk I/O speed (which might be at play here) or the inherent lameness of gzip (the latter of which is more predictable and doesn't explain this behavior).

**Comment by orodeh** [comment]
We use the local ephemeral disk, not EBS. It sounds like a `dx-docker` vs. native `docker` issue,
@geetduggal, can you take a look at this please?

**Comment by mlin** [comment]
+ @geetduggal 

I have seen this too with the >1GB viral-ngs image and my gut feeling is that it's a suboptimality of the docker2aci utility which dx-docker uses to pull the image layers. I doubt it's an issue with dxWDL specifically.

Speculation: while docker2aci [fetches different image layers in parallel](https://github.com/appc/docker2aci/pull/158), each individual layer is [downloaded on one sequential TCP connection](https://github.com/appc/docker2aci/blob/365911f6aa7f0a9a324a27bb6da0f7755df43041/lib/internal/backend/repository/repository2.go#L470). The viral-ngs image does have one layer which makes up a large majority of the total size. When docker2aci makes the TCP connection to S3 or whatever to retrieve it, it occasionally gets unlucky and hits a lousy remote host that can't push data at the expected speed (maybe it's overloaded or whatever).

`dx download` and other cloud transfer utilities smooth this over with multipart transfers, i.e. it uses many TCP connections to download small parts of the remote file in parallel, with individual part retries, so that a small % of lousy ones is well-tolerated. Maybe `docker pull` does that too.

**Comment by dpark01** [comment]
If you think it is the network itself that is being unpredictable and slow, we can try a few things:

- I can try an alternate registry just for kicks. Probably quay.io (which I think exposes raw S3 URLs in us-east)
- If you're sure docker2aci pull operations are inherently not fast, and if this is a general issue beyond my project, then you could consider creating a fetch_aci dx applet that dxWDL invokes prior to every other applet in its workflows: takes a docker tag string in and emits a ACI file. It would be kind of annoying the first time you ran the workflow in a given project, but each subsequent time, DNAnexus will likely cache those jobs and use the ACI files already living in the project. This is if you believe that multi-part downloads are making all the difference here (and that `dx download` of an ACI would beat `docker2aci` consistently). I mean, `dx download` ought to be able to pull down a 1.5GB ACI in 12 seconds.

That being said, in my own playing around, `rkt prepare viral-ngs.aci` takes about 3 mins, so the bulk of the time here isn't the network-limited download speed--it's whatever else it's doing to unpack it. But I'm willing to settle for a 3-5 minute spin up time as long as it's consistently 3-5 minutes. Don't know how rkt compares to what dx-docker is doing though.

**Comment by mlin** [comment]
@dpark01 this is the key excerpt of `dx watch job-F8G5KyQ09y3bJYjqB23XJgBQ` consistent with my admitted speculation:

```
2017-11-24 10:09:10 scaffold STDERR sha256:f4e5dc28016: 947 MB/1.53 GB
2017-11-24 10:09:11 scaffold STDERR sha256:f4e5dc28016: 961 MB/1.53 GB
2017-11-24 10:09:11 scaffold STDERR sha256:f4e5dc28016: 975 MB/1.53 GB
2017-11-24 10:09:12 scaffold STDERR sha256:f4e5dc28016: 989 MB/1.53 GB
2017-11-24 10:09:12 scaffold STDERR sha256:f4e5dc28016: 1.01 GB/1.53 GB
2017-11-24 10:09:15 scaffold STDERR sha256:f4e5dc28016: 1.22 GB/1.53 GB
2017-11-24 10:18:26 scaffold INFO CPU: 0% (8 cores) * Memory: 850/15038MB * Storage: 152GB free * Net: 3↓/0↑MBps
2017-11-24 10:28:26 scaffold INFO CPU: 0% (8 cores) * Memory: 849/15038MB * Storage: 152GB free * Net: 0↓/0↑MBps
2017-11-24 10:38:26 scaffold INFO CPU: 0% (8 cores) * Memory: 850/15038MB * Storage: 152GB free * Net: 0↓/0↑MBps
2017-11-24 10:44:24 scaffold STDERR sha256:f4e5dc28016: 1.31 GB/1.53 GB
2017-11-24 10:44:29 scaffold STDERR sha256:f4e5dc28016: 1.47 GB/1.53 GB
2017-11-24 10:47:52 scaffold STDERR Image Repo	broadinstitute/viral-ngs-dev
2017-11-24 10:47:52 scaffold STDERR Image Tag	1.18.2-110-g4a530c5-dp-dx-pull_request
2017-11-24 10:47:52 scaffold STDERR Image Size	5.3G
2017-11-24 10:47:52 scaffold STDERR Image ID	sha256:3f1a535db9d99f467b2d888b0bdf75ae645f7c937a8f17ffddee09d50497791f
```

`docker2aci` is printing progress messages as it's downloading the big 1.53GB layer, which goes at a healthy clip up until 1.22GB. Then, not much seems to happen for like half an hour, and then then the last 200MB come in quickly. I think this is a sporadic delay occurring in the transfer, before any of the decompression/unpacking occurs. I'll need to discuss possible workarounds for this with @geetduggal when he gets back from re:Invent

**Comment by geetduggal** [comment]
Interesting.  Yes, let's dig more into it.  One nice thing about the `dx-docker add-to-applet/create-asset` subcommands is that they cache the image on the platform and avoid all these network issues -- particularly handy when we venture into non-US regions.  However, this involves an additional step to update the cache every time the public repo is updated -- something I can understand you may want to avoid if at all possible :)

**Comment by mlin** [comment]
@dpark01 BTW I do think it would be worthwhile to try quay at least as a one-off workaround until Geet and I can get our heads together on this

**Comment by dpark01** [comment]
Yep, giving that a shot now!

**Comment by orodeh** [comment]
@geetduggal, this is a pure dx-docker issue, I am closing it here.

**Comment by dpark01** [comment]
(also, quay.io does seem to obviate this issue)
